#!/bin/sh
# postrm for openmediavault-agent-station
set -e

case "$1" in
    remove|purge|disappear)
        mkdir -p /var/cache/openmediavault/archives 2>/dev/null || true
        find /var/cache/openmediavault/ -maxdepth 1 -name "cache.*" -delete 2>/dev/null || true
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade)
        ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
